name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci

      - name: Release plugin
        run: >-
          qgis-plugin-ci
          release ${GITHUB_REF_NAME}
          --github-token ${{ secrets.GITHUB_TOKEN }}
          --qgis-token ${{ secrets.QGIS_PLUGIN_REPO_TOKEN }}
